"""empty message

Revision ID: 195fa9b51a5d
Revises: 2c26762d070b
Create Date: 2023-05-22 13:56:45.558606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195fa9b51a5d'
down_revision = '2c26762d070b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Comment', sa.Column('creation', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Comment', 'creation')
    # ### end Alembic commands ###
