version: "3.8"

services:
  api:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    entrypoint: ["bash", "./docker/entry.sh"]
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ../:/usr/src/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
